apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pol-ingr-router
  namespace: policy-test
spec:
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: pol-ingr-router
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operator.openshift.io/v1
            kind: IngressController
            metadata:
              name: default
              namespace: openshift-ingress-operator
            spec:
              replicas: 6
              tuningOptions:
                threadCount: 8
        remediationAction: enforce
        severity: low
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-test
  namespace: policy-test
spec:
  clusterSelector:
    matchExpressions:
    - key: environment
      operator: In
      values:
      - prod
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-pol-ingr-router
  namespace: policy-test
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-test-prod
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: pol-ingr-router-prod
